;;; post-init.el -*- no-byte-compile: t; lexical-binding: t; -*-

(add-to-list 'load-path (expand-file-name "~/.emacs.d/rc/"))

(require 'rc-delight)
(require 'rc-opts)
(require 'rc-fonts)
(require 'rc-keymaps)
(require 'rc-which-key)
(require 'rc-theme)
(require 'rc-dired)
(require 'rc-trashed)
(require 'rc-treesit)
(require 'rc-ace-window)
(require 'rc-avy)
(require 'rc-expand-region)
(require 'rc-editorconfig)
(require 'rc-mise)
(require 'rc-exec-path-from-shell)
(require 'rc-buffer-terminator)
(require 'rc-super-save)
(require 'rc-undo-fu)
(require 'rc-helpful)
(require 'rc-crux)
(require 'rc-nov)
(require 'rc-completion)
(require 'rc-consult)
(require 'rc-rg)
(require 'rc-magit)
(require 'rc-apheleia)
(require 'rc-eglot)
(require 'rc-python)
(require 'rc-json)
(require 'rc-go)
(require 'rc-elisp)
(require 'rc-markdown)
(require 'rc-typst)
(require 'rc-org)

(defun insert-previous-file-name ()
  (interactive)
  (let ((file-name (with-current-buffer (window-buffer (minibuffer-selected-window))
                     (file-name-nondirectory (buffer-file-name)))))
    (insert file-name)))

(define-key minibuffer-local-map (kbd "M-i") 'insert-previous-file-name)
