;;; post-init.el -*- no-byte-compile: t; lexical-binding: t; -*-

(add-to-list 'load-path (expand-file-name "~/.emacs.d/rc/"))

(require 'rc-delight)
(require 'rc-opts)
(require 'rc-fonts)
(require 'rc-keymaps)
(require 'rc-which-key)
(require 'rc-theme)
(require 'rc-dired)
(require 'rc-trashed)
(require 'rc-treesit)
(require 'rc-ace-window)
(require 'rc-avy)
(require 'rc-expand-region)
(require 'rc-editorconfig)
(require 'rc-mise)
(require 'rc-exec-path-from-shell)
(require 'rc-buffer-terminator)
(require 'rc-super-save)
(require 'rc-undo-fu)
(require 'rc-helpful)
(require 'rc-crux)
(require 'rc-nov)
(require 'rc-completion)
(require 'rc-consult)
(require 'rc-rg)
(require 'rc-magit)
(require 'rc-apheleia)
(require 'rc-eglot)
(require 'rc-python)
(require 'rc-json)
(require 'rc-go)
(require 'rc-elisp)
(require 'rc-markdown)
(require 'rc-typst)
(require 'rc-org)

(use-package devil
  :ensure t
  :vc (:url "https://github.com/fbrosda/devil"
            :branch "dev"
            :rev :newest)
  :hook (after-init . global-devil-mode)
  :bind
  ([remap describe-key] . devil-describe-key)
  :config
  (assoc-delete-all "%k SPC" devil-special-keys)
  (devil-set-key (kbd "j"))
  (setq devil-exit-key "k")
  (setq devil-all-keys-repeatable t)
  (setq devil-highlight-repeatable t)
  (setq devil-repeatable-keys '( ("%k p" "%k n" "%k b" "%k f" "%k a" "%k e")
                                 ("%k m n" "%k m p")
                                 ("%k m b" "%k m f" "%k m a" "%k m e")
                                 ("%k m m f" "%k m m b" "%k m m a" "%k m m e" "%k m m n" "%k m m p" "%k m m u" "%k m m d"))))
